// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-GB'

export type Locales =
	| 'en-GB'
	| 'es-ES'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * P​a​D​D​e​L​ ​w​e​b​s​i​t​e​ ​t​o​ ​i​n​t​e​r​a​c​t​ ​w​i​t​h​ ​m​o​d​e​l​s​ ​t​r​a​i​n​e​d​ ​t​o​ ​d​e​t​e​c​t​ ​P​a​r​k​i​n​s​o​n​'​s​ ​D​i​s​e​a​s​e​ ​m​a​d​e​ ​b​y​ ​t​h​e​ ​U​n​i​v​e​r​s​i​t​y​ ​o​f​ ​B​u​r​g​o​s
	 */
	PAGE_DESCRIPTION: string
	/**
	 * O​p​e​n​ ​l​a​n​g​u​a​g​e​ ​s​e​l​e​c​t​i​o​n
	 */
	LANGUAGE_SELECTION: string
	/**
	 * A​d​m​i​n​i​s​t​r​a​t​i​o​n
	 */
	ADMINISTRATION: string
	/**
	 * P​r​e​d​i​c​t
	 */
	PREDICT: string
	/**
	 * F​i​l​l​ ​i​n​ ​a​n​d​ ​s​e​n​d​ ​t​h​i​s​ ​f​o​r​m​ ​t​o​ ​r​e​c​i​e​v​e​ ​a​ ​p​r​e​d​i​c​t​i​o​n​.​ ​M​a​k​e​ ​s​u​r​e​ ​t​h​e​ ​v​i​d​e​o​ ​i​s​,​ ​a​t​ ​l​e​a​s​t​,​ ​1​5​ ​s​e​c​o​n​d​s​ ​l​o​n​g​.​ ​A​n​ ​e​x​a​m​p​l​e​ ​v​i​d​e​o​ ​c​a​n​ ​b​e​ ​f​o​u​n​d​ ​<​a​ ​t​a​r​g​e​t​=​"​_​b​l​a​n​k​"​ ​c​l​a​s​s​=​"​t​e​x​t​-​b​l​u​e​-​5​0​0​ ​d​a​r​k​:​t​e​x​t​-​b​l​u​e​-​5​0​0​ ​h​o​v​e​r​:​u​n​d​e​r​l​i​n​e​"​ ​h​r​e​f​=​"​h​t​t​p​s​:​/​/​y​o​u​t​u​.​b​e​/​S​Y​b​6​2​a​C​o​6​E​Q​"​>​h​e​r​e​<​/​a​>​.
	 */
	PREDICT_HELP: string
	/**
	 * L​e​f​t
	 */
	LEFT: string
	/**
	 * R​i​g​h​t
	 */
	RIGHT: string
	/**
	 * Y​o​u​r​ ​d​o​m​i​n​a​n​t​ ​h​a​n​d
	 */
	YOUR_DOMINANT_HAND: string
	/**
	 * H​a​n​d​ ​s​h​o​w​n​ ​i​n​ ​t​h​e​ ​v​i​d​e​o
	 */
	HAND_SHOWN_IN_VIDEO: string
	/**
	 * A​g​e
	 */
	AGE: string
	/**
	 * y​e​a​r​s
	 */
	YEARS: string
	/**
	 * S​e​x
	 */
	SEX: string
	/**
	 * M​a​l​e
	 */
	MALE: string
	/**
	 * F​e​m​a​l​e
	 */
	FEMALE: string
	/**
	 * V​i​d​e​o​ ​f​i​l​e
	 */
	VIDEO_FILE: string
	/**
	 * U​p​l​o​a​d​ ​v​i​d​e​o​ ​f​i​l​e
	 */
	UPLOAD_A_VIDEO_FILE: string
	/**
	 * U​p​l​o​a​d​ ​m​o​d​e​l​ ​f​i​l​e
	 */
	UPLOAD_A_MODEL_FILE: string
	/**
	 * o​r​ ​d​r​a​g​ ​a​n​d​ ​d​r​o​p
	 */
	OR_DRAG_AND_DROP: string
	/**
	 * S​e​n​d
	 */
	SEND: string
	/**
	 * U​n​i​v​e​r​s​i​d​a​d​ ​d​e​ ​B​u​r​g​o​s
	 */
	UNIVERSITY_OF_BURGOS: string
	/**
	 * L​o​g​ ​i​n
	 */
	LOG_IN: string
	/**
	 * U​s​e​r​n​a​m​e
	 */
	USERNAME: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	PASSWORD: string
	/**
	 * L​o​g​ ​i​n​ ​t​o​ ​y​o​u​r​ ​a​c​c​o​u​n​t
	 */
	LOG_IN_TO_YOUR_ACCOUNT: string
	/**
	 * B​a​c​k
	 */
	BACK: string
	/**
	 * L​o​g​ ​o​u​t
	 */
	LOG_OUT: string
	/**
	 * S​e​n​d​i​n​g​ ​d​a​t​a​.​.​.
	 */
	SENDING_DATA: string
	/**
	 * P​r​o​c​e​s​s​i​n​g​ ​d​a​t​a​,​ ​p​l​e​a​s​e​ ​d​o​n​'​t​ ​l​e​a​v​e​ ​t​h​e​ ​p​a​g​e​.​.​.
	 */
	PROCESSING_DATA: string
	/**
	 * S​o​u​r​c​e​ ​c​o​d​e
	 */
	SOURCE_CODE: string
	/**
	 * A​P​I​ ​d​o​c​u​m​e​n​t​a​t​i​o​n
	 */
	API_DOCS: string
	/**
	 * U​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​w​r​o​n​g​.
	 */
	USERNAME_OR_PASSWORD_WRONG: string
	/**
	 * A​c​c​o​r​d​i​n​g​ ​t​o​ ​t​h​e​ ​m​o​d​e​l​ ​u​s​e​d​,​ ​t​h​e​r​e​ ​i​s​ ​a​ ​{​p​e​r​c​e​n​t​a​g​e​}​%​ ​c​h​a​n​c​e​ ​t​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​P​a​r​k​i​n​s​o​n​'​s​ ​D​i​s​e​a​s​e​.​ ​P​l​e​a​s​e​ ​t​a​k​e​ ​t​h​i​s​ ​r​e​s​u​l​t​ ​w​i​t​h​ ​a​ ​b​i​g​ ​g​r​a​i​n​ ​o​f​ ​s​a​l​t​,​ ​i​t​ ​i​s​ ​i​n​ ​n​o​ ​w​a​y​ ​s​u​b​s​t​i​t​u​t​e​ ​f​o​r​ ​a​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​a​s​s​e​s​s​m​e​n​t​.​ ​I​f​ ​y​o​u​ ​s​u​s​p​e​c​t​ ​y​o​u​ ​m​i​g​h​t​ ​h​a​v​e​ ​P​a​r​k​i​n​s​o​n​'​s​ ​D​i​s​e​a​s​e​,​ ​p​l​e​a​s​e​ ​t​a​l​k​ ​w​i​t​h​ ​y​o​u​r​ ​d​o​c​t​o​r​.
	 * @param {string} percentage
	 */
	PREDICTION_RESULT_DESC: RequiredParams<'percentage'>
	/**
	 * T​h​e​r​e​ ​w​a​s​ ​a​ ​p​r​o​b​l​e​m
	 */
	THERE_WAS_A_PROBLEM: string
	/**
	 * C​a​n​'​t​ ​p​r​o​c​e​s​s​ ​v​i​d​e​o​,​ ​p​l​e​a​s​e​ ​c​h​e​c​k​ ​i​t​ ​o​u​t​.
	 */
	CANNOT_PROCESS_VIDEO: string
	/**
	 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​t​e​r​r​i​b​l​y​ ​w​r​o​n​g​.
	 */
	SOMETHING_WENT_WRONG: string
	/**
	 * P​r​e​d​i​c​t​i​o​n​ ​R​e​s​u​l​t
	 */
	PREDICTION_RESULT: string
	/**
	 * U​s​e​r​ ​m​a​n​a​g​e​m​e​n​t
	 */
	USER_MANAGEMENT: string
	/**
	 * A​ ​l​i​s​t​ ​o​f​ ​a​l​l​ ​t​h​e​ ​u​s​e​r​s​ ​i​n​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​i​n​c​l​u​d​i​n​g​ ​t​h​e​i​r​ ​n​a​m​e​,​ ​t​i​t​l​e​,​ ​e​m​a​i​l​ ​a​n​d​ ​r​o​l​e​.
	 */
	USER_MANAGEMENT_DESC: string
	/**
	 * A​d​d​ ​u​s​e​r
	 */
	ADD_USER: string
	/**
	 * I​D
	 */
	ID: string
	/**
	 * A​c​t​i​o​n​s
	 */
	ACTIONS: string
	/**
	 * D​e​l​e​t​e
	 */
	DELETE: string
	/**
	 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g​.
	 */
	PASSWORD_TOO_SHORT: string
	/**
	 * U​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​w​r​o​n​g​.
	 */
	LOGIN_FAILED: string
	/**
	 * T​h​i​s​ ​u​s​e​r​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
	 */
	USER_ALREADY_EXISTS: string
	/**
	 * U​s​e​r​n​a​m​e​s​ ​m​u​s​t​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g​.
	 */
	USERNAME_TOO_SHORT: string
	/**
	 * U​s​e​r​s
	 */
	USERS: string
	/**
	 * M​o​d​e​l​s
	 */
	MODELS: string
	/**
	 * A​d​d​ ​m​o​d​e​l
	 */
	ADD_MODEL: string
	/**
	 * M​o​d​e​l​ ​m​a​n​a​g​e​m​e​n​t
	 */
	MODEL_MANAGEMENT: string
	/**
	 * A​ ​l​i​s​t​ ​o​f​ ​a​l​l​ ​t​h​e​ ​m​o​d​e​l​s​ ​i​n​ ​t​h​e​ ​a​p​p​l​i​c​a​t​i​o​n​,​ ​y​o​u​ ​c​a​n​ ​u​p​l​o​a​d​ ​n​e​w​ ​m​o​d​e​l​s​ ​a​n​d​ ​s​e​l​e​c​t​ ​t​h​e​ ​d​e​f​a​u​l​t​ ​m​o​d​e​l​ ​t​o​ ​u​s​e​ ​f​o​r​ ​p​r​e​d​i​c​t​i​o​n​s​.
	 */
	MODEL_MANAGEMENT_DESC: string
	/**
	 * M​o​d​e​l​ ​n​a​m​e​s​ ​h​a​v​e​ ​t​o​ ​b​e​ ​a​t​ ​l​e​a​s​t​ ​3​ ​c​h​a​r​a​c​t​e​r​s​ ​l​o​n​g​.
	 */
	MODELNAME_TOO_SHORT: string
	/**
	 * F​e​t​c​h​i​n​g​ ​u​s​e​r​s​.​.​.
	 */
	FETCHING_USERS: string
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​f​e​t​c​h​ ​u​s​e​r​s​.
	 */
	USER_FETCH_ERROR: string
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​a​c​c​o​u​n​t​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
	 */
	DELETE_USER_CHECK: string
	/**
	 * D​e​l​e​t​e​ ​{​u​s​e​r​}​'​s​ ​a​c​c​o​u​n​t​?
	 * @param {string} user
	 */
	DELETE_USER_CHECK_TITLE: RequiredParams<'user'>
	/**
	 * C​a​n​c​e​l
	 */
	CANCEL: string
	/**
	 * C​r​e​a​t​e​ ​n​e​w​ ​u​s​e​r
	 */
	CREATE_NEW_USER: string
	/**
	 * C​r​e​a​t​e​ ​u​s​e​r
	 */
	CREATE_USER: string
	/**
	 * M​o​d​e​l​ ​w​i​t​h​ ​t​h​a​t​ ​n​a​m​e​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
	 */
	MODEL_NAME_ALREADY_EXISTS: string
	/**
	 * F​e​t​c​h​i​n​g​ ​m​o​d​e​l​s​.​.​.
	 */
	FETCHING_MODELS: string
	/**
	 * M​o​d​e​l​ ​n​a​m​e
	 */
	MODEL_NAME: string
	/**
	 * S​e​l​e​c​t​e​d
	 */
	SELECTED: string
	/**
	 * S​e​l​e​c​t
	 */
	SELECT: string
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​f​e​t​c​h​ ​m​o​d​e​l​s​.
	 */
	MODEL_FETCH_ERROR: string
	/**
	 * D​e​l​e​t​e​ ​m​o​d​e​l​ ​{​m​o​d​e​l​}​?
	 * @param {string} model
	 */
	DELETE_MODEL_CHECK_TITLE: RequiredParams<'model'>
	/**
	 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​m​o​d​e​l​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
	 */
	DELETE_MODEL_CHECK: string
	/**
	 * P​i​c​k​l​e​d​ ​b​i​n​a​r​y​ ​f​i​l​e​.
	 */
	PICKLE_FILE: string
	/**
	 * M​o​d​e​l​ ​f​i​l​e
	 */
	MODEL_FILE: string
	/**
	 * Y​o​u​ ​c​a​n​n​o​t​ ​r​e​m​o​v​e​ ​y​o​u​r​s​e​l​f
	 */
	CANT_REMOVE_YOURSELF: string
	/**
	 * T​h​i​s​ ​u​s​e​r​ ​c​a​n​n​o​t​ ​b​e​ ​r​e​m​o​v​e​d
	 */
	CANT_REMOVE_THIS_USER: string
	/**
	 * A​b​o​u​t
	 */
	ABOUT: string
	/**
	 * 
​	​T​h​i​s​ ​w​e​b​ ​a​p​p​l​i​c​a​t​i​o​n​ ​i​s​ ​p​a​r​t​ ​o​f​ ​t​h​e​ ​f​i​n​a​l​ ​d​e​g​r​e​e​ ​p​r​o​j​e​c​t​ ​m​a​d​e​ ​b​y​ ​C​a​t​a​l​i​n​ ​A​n​d​r​e​i​ ​C​a​c​u​c​i​
​	​u​n​d​e​r​ ​t​h​e​ ​s​u​p​e​r​v​i​s​i​o​n​ ​o​f​ ​A​l​i​c​i​a​ ​O​l​i​v​a​r​e​s​ ​G​i​l​ ​a​n​d​ ​Á​l​v​a​r​ ​A​r​n​a​i​z​ ​G​o​n​z​á​l​e​z​ ​i​n​ ​t​h​e​ ​f​r​a​m​e​ ​o​f​ ​p​r​o​j​e​c​t​ ​F​I​S​
​	​"​S​t​u​d​y​ ​o​f​ ​t​h​e​ ​f​e​a​s​i​b​i​l​i​t​y​ ​a​n​d​ ​c​o​s​t​ ​e​f​f​e​c​t​i​v​e​n​e​s​s​ ​o​f​ ​u​s​i​n​g​ ​t​e​l​e​m​e​d​i​c​i​n​e​ ​w​i​t​h​ ​a​ ​m​u​l​t​i​d​i​s​c​i​p​l​i​n​a​r​ ​t​e​a​m​
​	​f​o​r​ ​t​h​e​ ​p​r​e​v​e​n​t​i​o​n​ ​o​f​ ​f​a​l​l​s​ ​i​n​ ​P​a​r​k​i​n​s​o​n​'​s​ ​d​i​s​e​s​a​s​e​"​.
	 */
	ABOUT_P1: string
	/**
	 * T​h​i​s​ ​p​r​o​j​e​c​t​ ​w​o​u​l​d​ ​n​o​t​ ​h​a​v​e​ ​b​e​e​n​ ​p​o​s​s​i​b​l​e​ ​w​i​t​h​o​u​t​ ​t​h​e​ ​h​e​l​p​
​	​o​f​ ​t​h​e​ ​P​a​r​k​i​n​s​o​n​'​s​ ​a​s​s​o​c​i​a​t​i​o​n​ ​o​f​ ​B​u​r​g​o​s​,​ ​t​h​e​ ​s​t​a​f​f​ ​f​r​o​m​ ​t​h​e​ ​U​n​i​v​e​r​s​i​t​a​r​y​ ​H​o​s​p​i​t​a​l​
​	​o​f​ ​B​u​r​g​o​s​,​ ​D​r​.​ ​E​s​t​h​e​r​ ​C​u​b​o​'​s​ ​t​e​a​m​ ​a​n​d​ ​t​h​e​ ​p​e​o​p​l​e​ ​w​h​o​ ​v​o​l​u​n​t​a​r​i​l​y​ ​s​u​p​p​l​i​e​d​ ​t​h​e​ ​v​i​d​e​o​s​.
	 */
	ABOUT_P2: string
}

export type TranslationFunctions = {
	/**
	 * PaDDeL website to interact with models trained to detect Parkinson's Disease made by the University of Burgos
	 */
	PAGE_DESCRIPTION: () => LocalizedString
	/**
	 * Open language selection
	 */
	LANGUAGE_SELECTION: () => LocalizedString
	/**
	 * Administration
	 */
	ADMINISTRATION: () => LocalizedString
	/**
	 * Predict
	 */
	PREDICT: () => LocalizedString
	/**
	 * Fill in and send this form to recieve a prediction. Make sure the video is, at least, 15 seconds long. An example video can be found <a target="_blank" class="text-blue-500 dark:text-blue-500 hover:underline" href="https://youtu.be/SYb62aCo6EQ">here</a>.
	 */
	PREDICT_HELP: () => LocalizedString
	/**
	 * Left
	 */
	LEFT: () => LocalizedString
	/**
	 * Right
	 */
	RIGHT: () => LocalizedString
	/**
	 * Your dominant hand
	 */
	YOUR_DOMINANT_HAND: () => LocalizedString
	/**
	 * Hand shown in the video
	 */
	HAND_SHOWN_IN_VIDEO: () => LocalizedString
	/**
	 * Age
	 */
	AGE: () => LocalizedString
	/**
	 * years
	 */
	YEARS: () => LocalizedString
	/**
	 * Sex
	 */
	SEX: () => LocalizedString
	/**
	 * Male
	 */
	MALE: () => LocalizedString
	/**
	 * Female
	 */
	FEMALE: () => LocalizedString
	/**
	 * Video file
	 */
	VIDEO_FILE: () => LocalizedString
	/**
	 * Upload video file
	 */
	UPLOAD_A_VIDEO_FILE: () => LocalizedString
	/**
	 * Upload model file
	 */
	UPLOAD_A_MODEL_FILE: () => LocalizedString
	/**
	 * or drag and drop
	 */
	OR_DRAG_AND_DROP: () => LocalizedString
	/**
	 * Send
	 */
	SEND: () => LocalizedString
	/**
	 * Universidad de Burgos
	 */
	UNIVERSITY_OF_BURGOS: () => LocalizedString
	/**
	 * Log in
	 */
	LOG_IN: () => LocalizedString
	/**
	 * Username
	 */
	USERNAME: () => LocalizedString
	/**
	 * Password
	 */
	PASSWORD: () => LocalizedString
	/**
	 * Log in to your account
	 */
	LOG_IN_TO_YOUR_ACCOUNT: () => LocalizedString
	/**
	 * Back
	 */
	BACK: () => LocalizedString
	/**
	 * Log out
	 */
	LOG_OUT: () => LocalizedString
	/**
	 * Sending data...
	 */
	SENDING_DATA: () => LocalizedString
	/**
	 * Processing data, please don't leave the page...
	 */
	PROCESSING_DATA: () => LocalizedString
	/**
	 * Source code
	 */
	SOURCE_CODE: () => LocalizedString
	/**
	 * API documentation
	 */
	API_DOCS: () => LocalizedString
	/**
	 * Username or password wrong.
	 */
	USERNAME_OR_PASSWORD_WRONG: () => LocalizedString
	/**
	 * According to the model used, there is a {percentage}% chance that you have Parkinson's Disease. Please take this result with a big grain of salt, it is in no way substitute for a professional assessment. If you suspect you might have Parkinson's Disease, please talk with your doctor.
	 */
	PREDICTION_RESULT_DESC: (arg: { percentage: string }) => LocalizedString
	/**
	 * There was a problem
	 */
	THERE_WAS_A_PROBLEM: () => LocalizedString
	/**
	 * Can't process video, please check it out.
	 */
	CANNOT_PROCESS_VIDEO: () => LocalizedString
	/**
	 * Something went terribly wrong.
	 */
	SOMETHING_WENT_WRONG: () => LocalizedString
	/**
	 * Prediction Result
	 */
	PREDICTION_RESULT: () => LocalizedString
	/**
	 * User management
	 */
	USER_MANAGEMENT: () => LocalizedString
	/**
	 * A list of all the users in your account including their name, title, email and role.
	 */
	USER_MANAGEMENT_DESC: () => LocalizedString
	/**
	 * Add user
	 */
	ADD_USER: () => LocalizedString
	/**
	 * ID
	 */
	ID: () => LocalizedString
	/**
	 * Actions
	 */
	ACTIONS: () => LocalizedString
	/**
	 * Delete
	 */
	DELETE: () => LocalizedString
	/**
	 * Password must be at least 8 characters long.
	 */
	PASSWORD_TOO_SHORT: () => LocalizedString
	/**
	 * Username or password wrong.
	 */
	LOGIN_FAILED: () => LocalizedString
	/**
	 * This user already exists.
	 */
	USER_ALREADY_EXISTS: () => LocalizedString
	/**
	 * Usernames must be at least 3 characters long.
	 */
	USERNAME_TOO_SHORT: () => LocalizedString
	/**
	 * Users
	 */
	USERS: () => LocalizedString
	/**
	 * Models
	 */
	MODELS: () => LocalizedString
	/**
	 * Add model
	 */
	ADD_MODEL: () => LocalizedString
	/**
	 * Model management
	 */
	MODEL_MANAGEMENT: () => LocalizedString
	/**
	 * A list of all the models in the application, you can upload new models and select the default model to use for predictions.
	 */
	MODEL_MANAGEMENT_DESC: () => LocalizedString
	/**
	 * Model names have to be at least 3 characters long.
	 */
	MODELNAME_TOO_SHORT: () => LocalizedString
	/**
	 * Fetching users...
	 */
	FETCHING_USERS: () => LocalizedString
	/**
	 * Could not fetch users.
	 */
	USER_FETCH_ERROR: () => LocalizedString
	/**
	 * Are you sure you want to permanently delete this account? This action cannot be undone.
	 */
	DELETE_USER_CHECK: () => LocalizedString
	/**
	 * Delete {user}'s account?
	 */
	DELETE_USER_CHECK_TITLE: (arg: { user: string }) => LocalizedString
	/**
	 * Cancel
	 */
	CANCEL: () => LocalizedString
	/**
	 * Create new user
	 */
	CREATE_NEW_USER: () => LocalizedString
	/**
	 * Create user
	 */
	CREATE_USER: () => LocalizedString
	/**
	 * Model with that name already exists.
	 */
	MODEL_NAME_ALREADY_EXISTS: () => LocalizedString
	/**
	 * Fetching models...
	 */
	FETCHING_MODELS: () => LocalizedString
	/**
	 * Model name
	 */
	MODEL_NAME: () => LocalizedString
	/**
	 * Selected
	 */
	SELECTED: () => LocalizedString
	/**
	 * Select
	 */
	SELECT: () => LocalizedString
	/**
	 * Could not fetch models.
	 */
	MODEL_FETCH_ERROR: () => LocalizedString
	/**
	 * Delete model {model}?
	 */
	DELETE_MODEL_CHECK_TITLE: (arg: { model: string }) => LocalizedString
	/**
	 * Are you sure you want to permanently delete this model? This action cannot be undone.
	 */
	DELETE_MODEL_CHECK: () => LocalizedString
	/**
	 * Pickled binary file.
	 */
	PICKLE_FILE: () => LocalizedString
	/**
	 * Model file
	 */
	MODEL_FILE: () => LocalizedString
	/**
	 * You cannot remove yourself
	 */
	CANT_REMOVE_YOURSELF: () => LocalizedString
	/**
	 * This user cannot be removed
	 */
	CANT_REMOVE_THIS_USER: () => LocalizedString
	/**
	 * About
	 */
	ABOUT: () => LocalizedString
	/**
	 * 
	This web application is part of the final degree project made by Catalin Andrei Cacuci
	under the supervision of Alicia Olivares Gil and Álvar Arnaiz González in the frame of project FIS
	"Study of the feasibility and cost effectiveness of using telemedicine with a multidisciplinar team
	for the prevention of falls in Parkinson's disesase".
	 */
	ABOUT_P1: () => LocalizedString
	/**
	 * This project would not have been possible without the help
	of the Parkinson's association of Burgos, the staff from the Universitary Hospital
	of Burgos, Dr. Esther Cubo's team and the people who voluntarily supplied the videos.
	 */
	ABOUT_P2: () => LocalizedString
}

export type Formatters = {}
